name: Run and publish python program

on:
  push:
    branches: [ master ]

jobs:
  run-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Install dependencies and init ENV
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Run main.py
        run: |
          python main.py
          cd ${{steps.date.outputs.today}}
          echo "IP_PATH=$pwd" >> $GITHUB_ENV







      - name: Upload Firmware To Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{env.DATE}} IPs_range
          tag: ${{env.DATE}} IPs_range
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: ${{env.IP_PATH}}
          body: |
            这是根据大洲分布IP的IP CIDR块list