name: Run and publish python program

on:
  push:
    branches: [ master ]

jobs:
  run-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
      - name: Zip output directory
        run: zip -r output-${{ steps.date.outputs.date }}.zip . -i output-${{ steps.date.outputs.date }}/*.*
        working-directory: ${{ steps.date.outputs.date }}
      - name: Upload ZIP asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output-${{ steps.date.outputs.date }}.zip
          asset_name: output-${{ steps.date.outputs.date }}.zip
          asset_content_type: application/zip
